######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 1 20:56:13 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += camera.h image_process.h W.h
SOURCES += camera.c image_process.c main.cpp W.cpp
