#############################################################################
# Makefile for building: Lab07
# Generated by qmake (2.01a) (Qt 4.7.4) on: Tue Dec 1 20:56:13 2015
# Project:  Lab07.pro
# Template: app
# Command: /opt/qt-pandaboard-lib/bin/qmake -spec /opt/qt-pandaboard-lib/mkspecs/qws/linux-omap4430-g++ -o Makefile Lab07.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc
CXX           = arm-none-linux-gnueabi-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O3 -march=armv7-a -mtune=cortex-a9 -mfpu=neon -mfloat-abi=softfp -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O3 -march=armv7-a -mtune=cortex-a9 -mfpu=neon -mfloat-abi=softfp -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/opencvlib_arm/include -I/opt/qt-pandaboard-lib/mkspecs/qws/linux-omap4430-g++ -I. -I/opt/qt-pandaboard-lib/include/QtCore -I/opt/qt-pandaboard-lib/include/QtNetwork -I/opt/qt-pandaboard-lib/include/QtGui -I/opt/qt-pandaboard-lib/include -I. -I.
LINK          = arm-none-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-pandaboard-lib/lib
LIBS          = $(SUBLIBS)  -L/opt/opencvlib_arm/lib -lopencv_core -lopencv_objdetect -lopencv_highgui -lopencv_imgproc -L/opt/qt-pandaboard-lib//lib -lQtGui -L/opt/qt-pandaboard-lib//lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /opt/qt-pandaboard-lib/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-none-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = camera.c \
		image_process.c \
		main.cpp \
		W.cpp moc_W.cpp
OBJECTS       = camera.o \
		image_process.o \
		main.o \
		W.o \
		moc_W.o
DIST          = /opt/qt-pandaboard-lib/mkspecs/common/g++.conf \
		/opt/qt-pandaboard-lib/mkspecs/common/unix.conf \
		/opt/qt-pandaboard-lib/mkspecs/common/linux.conf \
		/opt/qt-pandaboard-lib/mkspecs/common/qws.conf \
		/opt/qt-pandaboard-lib/mkspecs/qconfig.pri \
		/opt/qt-pandaboard-lib/mkspecs/modules/qt_webkit_version.pri \
		/opt/qt-pandaboard-lib/mkspecs/features/qt_functions.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/qt_config.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/exclusive_builds.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/default_pre.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/release.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/default_post.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/warn_on.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/qt.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/unix/thread.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/moc.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/resources.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/uic.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/yacc.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/lex.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/include_source_dir.prf \
		Lab07.pro
QMAKE_TARGET  = Lab07
DESTDIR       = 
TARGET        = Lab07

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Lab07.pro  /opt/qt-pandaboard-lib/mkspecs/qws/linux-omap4430-g++/qmake.conf /opt/qt-pandaboard-lib/mkspecs/common/g++.conf \
		/opt/qt-pandaboard-lib/mkspecs/common/unix.conf \
		/opt/qt-pandaboard-lib/mkspecs/common/linux.conf \
		/opt/qt-pandaboard-lib/mkspecs/common/qws.conf \
		/opt/qt-pandaboard-lib/mkspecs/qconfig.pri \
		/opt/qt-pandaboard-lib/mkspecs/modules/qt_webkit_version.pri \
		/opt/qt-pandaboard-lib/mkspecs/features/qt_functions.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/qt_config.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/exclusive_builds.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/default_pre.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/release.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/default_post.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/warn_on.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/qt.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/unix/thread.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/moc.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/resources.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/uic.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/yacc.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/lex.prf \
		/opt/qt-pandaboard-lib/mkspecs/features/include_source_dir.prf \
		/opt/qt-pandaboard-lib/lib/libQtGui.prl \
		/opt/qt-pandaboard-lib/lib/libQtNetwork.prl \
		/opt/qt-pandaboard-lib/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qt-pandaboard-lib/mkspecs/qws/linux-omap4430-g++ -o Makefile Lab07.pro
/opt/qt-pandaboard-lib/mkspecs/common/g++.conf:
/opt/qt-pandaboard-lib/mkspecs/common/unix.conf:
/opt/qt-pandaboard-lib/mkspecs/common/linux.conf:
/opt/qt-pandaboard-lib/mkspecs/common/qws.conf:
/opt/qt-pandaboard-lib/mkspecs/qconfig.pri:
/opt/qt-pandaboard-lib/mkspecs/modules/qt_webkit_version.pri:
/opt/qt-pandaboard-lib/mkspecs/features/qt_functions.prf:
/opt/qt-pandaboard-lib/mkspecs/features/qt_config.prf:
/opt/qt-pandaboard-lib/mkspecs/features/exclusive_builds.prf:
/opt/qt-pandaboard-lib/mkspecs/features/default_pre.prf:
/opt/qt-pandaboard-lib/mkspecs/features/release.prf:
/opt/qt-pandaboard-lib/mkspecs/features/default_post.prf:
/opt/qt-pandaboard-lib/mkspecs/features/warn_on.prf:
/opt/qt-pandaboard-lib/mkspecs/features/qt.prf:
/opt/qt-pandaboard-lib/mkspecs/features/unix/thread.prf:
/opt/qt-pandaboard-lib/mkspecs/features/moc.prf:
/opt/qt-pandaboard-lib/mkspecs/features/resources.prf:
/opt/qt-pandaboard-lib/mkspecs/features/uic.prf:
/opt/qt-pandaboard-lib/mkspecs/features/yacc.prf:
/opt/qt-pandaboard-lib/mkspecs/features/lex.prf:
/opt/qt-pandaboard-lib/mkspecs/features/include_source_dir.prf:
/opt/qt-pandaboard-lib/lib/libQtGui.prl:
/opt/qt-pandaboard-lib/lib/libQtNetwork.prl:
/opt/qt-pandaboard-lib/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qt-pandaboard-lib/mkspecs/qws/linux-omap4430-g++ -o Makefile Lab07.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Lab071.0.0 || $(MKDIR) .tmp/Lab071.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Lab071.0.0/ && $(COPY_FILE) --parents camera.h image_process.h W.h .tmp/Lab071.0.0/ && $(COPY_FILE) --parents camera.c image_process.c main.cpp W.cpp .tmp/Lab071.0.0/ && (cd `dirname .tmp/Lab071.0.0` && $(TAR) Lab071.0.0.tar Lab071.0.0 && $(COMPRESS) Lab071.0.0.tar) && $(MOVE) `dirname .tmp/Lab071.0.0`/Lab071.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Lab071.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_W.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_W.cpp
moc_W.cpp: W.h
	/opt/qt-pandaboard-lib//bin/moc $(DEFINES) $(INCPATH) W.h -o moc_W.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

camera.o: camera.c camera.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o camera.o camera.c

image_process.o: image_process.c image_process.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o image_process.o image_process.c

main.o: main.cpp W.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

W.o: W.cpp W.h \
		camera.h \
		image_process.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o W.o W.cpp

moc_W.o: moc_W.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_W.o moc_W.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

